name: switchfin
summary: switchfin
description: |
  third-party PC player for Jellyfin
version: "0.5.2"
grade: stable
icon: ../resources/icon/icon.png
base: core20
confinement: strict
license: Apache-2.0

apps:
  switchfin:
    command: bin/desktop-launch $SNAP/usr/bin/Switchfin
    plugs:
      - desktop
      - x11
      - opengl
      - network

layout:
  /usr/resources:
    bind: $SNAP/usr/resources

parts:
  libmpv:
    source: https://github.com/mpv-player/mpv/archive/v0.36.0.tar.gz
    source-type: tar
    plugin: meson
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --default-library=shared
      - -Dcplayer=false
      - -Dlibmpv=true
      - -Dtests=false
      - -Dplain-gl=enabled
      - -Dlibarchive=disabled
      - -Dalsa=disabled
      - -Dlua=disabled
    build-packages:
      - libpulse-dev
      - libuchardet-dev
    stage-packages:
      - libdrm2
      - libpulse0
      - libuchardet0
    prime:
      - -etc
      - -usr/bin
      - -usr/share
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
    after:
      - ffmpeg
      - libass

  ffmpeg:
    source: https://ffmpeg.org/releases/ffmpeg-7.1.tar.xz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - --enable-shared
      - --disable-static
      - --enable-nonfree
      - --enable-openssl
      - --disable-doc
      - --disable-programs
      - --disable-protocols
      - --disable-encoders
      - --disable-muxers
      - --disable-filters
      - --enable-protocol=file,http,tcp,udp,hls,https,tls,httpproxy
      - --enable-filter=hflip,vflip,transpose
      - --enable-libv4l2
      - --enable-libdav1d
      - --enable-libfontconfig
      - --enable-libfreetype
    build-packages:
      - nasm
      - libfontconfig1-dev
      - libssl-dev
      - libv4l-dev
      - libva-dev
      - libvdpau-dev
    stage-packages:
      - libfontconfig1
      - libssl1.1
      - libv4l-0
      - libva-drm2
      - libva-glx2
      - libvdpau1
    after:
      - dav1d
      - libass
    prime:
      - -etc
      - -usr/bin
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  dav1d:
    plugin: meson
    source: https://downloads.videolan.org/pub/videolan/dav1d/1.4.3/dav1d-1.4.3.tar.xz
    source-type: tar
    meson-parameters:
      - --prefix=/usr
      - --buildtype=release
      - --strip
      - -Denable_tools=false
      - -Denable_tests=false
    build-packages:
      - libxxhash-dev
    stage-packages:
      - libxxhash0
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  libass:
    source: https://github.com/libass/libass/releases/download/0.17.3/libass-0.17.3.tar.gz
    source-type: tar
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --libdir=/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
      - --disable-static
    build-packages:
      - libfribidi-dev
      - libharfbuzz-dev
      - libfontconfig1-dev
    stage-packages:
      - libfribidi0
      - libharfbuzz0b
      - libfontconfig1
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share

  glfw:
    plugin: cmake
    source: https://github.com/dragonflylee/glfw/archive/switchfin.tar.gz
    source-type: tar
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=ON
      - -DGLFW_BUILD_WAYLAND=OFF
      - -DGLFW_BUILD_EXAMPLES=OFF
      - -DGLFW_BUILD_TESTS=OFF
      - -DGLFW_BUILD_DOCS=OFF
    build-packages:
      - xorg-dev
      - libdbus-1-dev
    stage-packages:
      - libx11-6
    prime:
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/share
    after:
      - desktop-glib-only

  desktop-glib-only:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-subdir: glib-only
    plugin: make
    build-packages:
      - libglib2.0-dev
    stage-packages:
      - libglib2.0-bin
    prime:
      - -usr/share

  curl:
    source: https://curl.se/download/curl-8.7.1.tar.xz
    source-type: tar
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCMAKE_BUILD_TYPE=Release
      - -DBUILD_SHARED_LIBS=ON
      - -DHTTP_ONLY=ON
      - -DCURL_USE_OPENSSL=ON
      - -DCURL_DISABLE_PROGRESS_METER=ON
      - -DCURL_USE_OPENSSL=OFF
      - -DBUILD_CURL_EXE=OFF
      - -DBUILD_TESTING=OFF
      - -DBUILD_LIBCURL_DOCS=OFF
      - -DUSE_LIBIDN2=OFF
      - -DCURL_USE_LIBSSH2=OFF
      - -DCURL_USE_LIBPSL=OFF
    build-environment:
      - CMAKE_PREFIX_PATH: $SNAPCRAFT_STAGE/usr
    build-packages:
      - libssl-dev
    stage-packages:
      - libssl1.1
    prime:
      - -usr/bin
      - -usr/include
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pkgconfig
      - -usr/lib/$SNAPCRAFT_ARCH_TRIPLET/cmake

  switchfin:
    plugin: cmake
    source: ".."
    source-type: local
    cmake-parameters:
      - -DPLATFORM_DESKTOP=ON
      - -DCMAKE_BUILD_TYPE=Release
      - -DUSE_SYSTEM_GLFW=ON
      - -DCMAKE_INSTALL=ON
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DCUSTOM_RESOURCES_DIR=/usr
    build-environment:
      - CMAKE_PREFIX_PATH: $SNAPCRAFT_STAGE/usr
      - LD_LIBRARY_PATH: $SNAPCRAFT_STAGE/usr/lib/$SNAPCRAFT_ARCH_TRIPLET
    build-packages:
      - g++
      - libwebp-dev
    stage-packages:
      - libglib2.0-bin
    after:
      - glfw
      - curl
      - libmpv
    prime:
      - -etc
      - -usr/bin/fc-*
