/*
    pleNx — "Playlists" sidebar tab (see playlists_tab.hpp).
*/

#include "tab/playlists_tab.hpp"
#include "tab/playlist_view.hpp"
#include "api/plex.hpp"
#include "api/backend.hpp"
#include "view/recycling_grid.hpp"
#include "view/svg_image.hpp"
#include "view/video_card.hpp"
#include "view/auto_tab_frame.hpp"
#include "utils/image.hpp"
#include "utils/keybind.hpp"

using namespace brls::literals;  // for _i18n

/// Square playlist cards: poster (thumb, otherwise 1:1 composite)
/// + title + "N items".
/// Not a VideoDataSource: the X/long-press context menu of VideoCardCell
/// (which casts to VideoDataSource) stays inert here, on purpose — no
/// contextual action applies to a playlist.
class PlaylistsDataSource : public RecyclingGridDataSource {
public:
    using MediaList = std::vector<plex::Item>;

    explicit PlaylistsDataSource(const MediaList& r) : list(std::move(r)) {}

    size_t getItemCount() override { return this->list.size(); }

    RecyclingGridItem* cellForRow(RecyclingView* recycler, size_t index) override {
        VideoCardCell* cell = dynamic_cast<VideoCardCell*>(recycler->dequeueReusableCell("Cell"));
        auto& item = this->list.at(index);
        cell->setId(item.ratingKey);
        cell->labelTitle->setText(item.title);
        if (item.leafCount > 0) {
            cell->labelExt->setText(fmt::format("{} {}", item.leafCount,
                item.leafCount > 1 ? "main/playlist/items"_i18n : "main/playlist/item"_i18n));
            cell->labelExt->setVisibility(brls::Visibility::VISIBLE);
        } else {
            cell->labelExt->setVisibility(brls::Visibility::GONE);
        }
        // recycled cell: purge the previous playlist's poster
        // (Image::load ignores an empty path without clearing the texture)
        cell->picture->clear();
        // custom poster (thumb) takes priority; fallback to the 1:1
        // mosaic generated by the server
        Image::load(cell->picture, item.thumb.empty() ? item.composite : item.thumb, 325);
        // neither "watched" badge nor progress bar on a playlist
        cell->badgeTopRight->setVisibility(brls::Visibility::GONE);
        cell->rectProgress->getParent()->setVisibility(brls::Visibility::GONE);
        return cell;
    }

    void onItemSelected(brls::Box* recycler, size_t index) override {
        auto& item = this->list.at(index);
        ui::presentDetail(recycler, new PlaylistView(item));
    }

    void clearData() override { this->list.clear(); }

    void appendData(const MediaList& data) { this->list.insert(this->list.end(), data.begin(), data.end()); }

private:
    MediaList list;
};

PlaylistsTab::PlaylistsTab() {
    brls::Logger::debug("PlaylistsTab: create");
    this->inflateFromXMLRes("xml/tabs/playlists.xml");

    this->recycler->registerCell("Cell", VideoCardCell::create);
    this->recycler->onNextPage([this]() { this->doRequest(); });

    auto actionRefresh = [this](...) {
        this->startIndex = 0;
        this->recycler->showSkeleton();
        this->doRequest();
        return true;
    };
    this->recycler->registerAction("hints/refresh"_i18n, brls::BUTTON_BACK, actionRefresh);
    this->registerAction(KeyBind::getRefresh(), actionRefresh);

    this->doRequest();
}

brls::View* PlaylistsTab::getDefaultFocus() { return this->recycler; }

brls::View* PlaylistsTab::create() { return new PlaylistsTab(); }

void PlaylistsTab::doRequest() {
    ASYNC_RETAIN
    // requested offset, not r.StartIndex: Jellyfin/Emby omit StartIndex on an
    // empty past-the-end page (it parses to 0) and would wipe a filled grid
    size_t reqStart = this->startIndex;
    AppConfig::instance().backend().getPlaylists(this->startIndex, this->pageSize,
        [ASYNC_TOKEN, reqStart](const media::Container<media::Item>& r) {
            ASYNC_RELEASE
            this->startIndex = reqStart + this->pageSize;
            if (r.TotalRecordCount == 0 && reqStart == 0) {
                this->recycler->setEmpty();
            } else if (reqStart == 0) {
                this->recycler->setDataSource(new PlaylistsDataSource(r.Items));
            } else if (r.Items.size() > 0) {
                auto dataSrc = dynamic_cast<PlaylistsDataSource*>(this->recycler->getDataSource());
                dataSrc->appendData(r.Items);
                this->recycler->notifyDataChanged();
            }
        },
        [ASYNC_TOKEN, reqStart](const std::string& ex) {
            ASYNC_RELEASE
            if (reqStart > 0) {
                brls::Application::notify(ex);
            } else {
                this->recycler->setError(ex);
            }
        });
}
