/*
    pleNx — neutral pivot model shared by every media backend.

    These structs are produced by each backend (Plex, Jellyfin/Emby, Stremio):
    the UI consumes `media::Item` / `media::Container<T>` and never sees a
    provider-specific shape. See MULTI_BACKEND.md §2.

    Units: durations/positions in MILLISECONDS, timestamps in epoch SECONDS
    (each backend converts: Jellyfin ticks ÷ 10 000 = ms, Stremio "120m" parsed).

    NOTE: the `from_json` overloads below decode the PLEX wire shape (ratingKey,
    viewOffset, MediaContainer...). They are the Plex backend's default mapper,
    kept here for now; Jellyfin/Stremio backends use their own explicit mappers
    and never rely on these. Extracting them fully into PlexBackend is a noted
    cleanup (MULTI_BACKEND.md §9).
*/

#pragma once

#include <string>
#include <vector>
#include <cstring>
#include <nlohmann/json.hpp>

namespace media {

/// ---- Generic media type strings (Item::type) -------------------------------
const std::string mediaTypeMovie = "movie";
const std::string mediaTypeShow = "show";
const std::string mediaTypeSeason = "season";
const std::string mediaTypeEpisode = "episode";
const std::string mediaTypeClip = "clip";
const std::string mediaTypeCollection = "collection";
const std::string mediaTypePhoto = "photo";
const std::string mediaTypePlaylist = "playlist";

/// Normalized streamType values (each backend maps onto these)
const int streamTypeVideo = 1;
const int streamTypeAudio = 2;
const int streamTypeSubtitle = 3;

/// ---- Lenient JSON helpers ---------------------------------------------------
/// Servers omit absent fields and sometimes return numbers as strings; these
/// helpers absorb both cases without throwing. Generic — usable by any mapper.
inline std::string jstr(const nlohmann::json& j, const char* key, const std::string& def = "") {
    auto it = j.find(key);
    if (it == j.end()) return def;
    if (it->is_string()) return it->get<std::string>();
    if (it->is_number_integer()) return std::to_string(it->get<int64_t>());
    return def;
}

inline int64_t jint(const nlohmann::json& j, const char* key, int64_t def = 0) {
    auto it = j.find(key);
    if (it == j.end()) return def;
    if (it->is_number()) return it->get<int64_t>();
    if (it->is_string()) {
        try {
            return std::stoll(it->get<std::string>());
        } catch (...) {
        }
    }
    return def;
}

inline double jnum(const nlohmann::json& j, const char* key, double def = 0.0) {
    auto it = j.find(key);
    if (it == j.end()) return def;
    if (it->is_number()) return it->get<double>();
    if (it->is_string()) {
        try {
            return std::stod(it->get<std::string>());
        } catch (...) {
        }
    }
    return def;
}

inline bool jbool(const nlohmann::json& j, const char* key, bool def = false) {
    auto it = j.find(key);
    if (it == j.end()) return def;
    if (it->is_boolean()) return it->get<bool>();
    if (it->is_number()) return it->get<int64_t>() != 0;
    if (it->is_string()) return it->get<std::string>() == "1" || it->get<std::string>() == "true";
    return def;
}

/// Arrays of `[{"tag": "..."}]` objects (Genre, Director, Writer...)
inline std::vector<std::string> jtags(const nlohmann::json& j, const char* key) {
    std::vector<std::string> out;
    auto it = j.find(key);
    if (it == j.end() || !it->is_array()) return out;
    for (auto& e : *it) out.push_back(jstr(e, "tag"));
    return out;
}

/// ---- Media models ---------------------------------------------------------------

/// Library / catalog (a browsable container or a genre directory)
struct Section {
    std::string key;   // numeric id of the section (as a string)
    std::string type;  // movie | show | artist | photo
    std::string title;
    std::string uuid;
    std::string composite;  // poster mosaic generated by the server
    std::string art;
    bool hidden = false;
};
inline void from_json(const nlohmann::json& j, Section& r) {
    r.key = jstr(j, "key");
    r.type = jstr(j, "type");
    r.title = jstr(j, "title");
    r.uuid = jstr(j, "uuid");
    r.composite = jstr(j, "composite");
    r.art = jstr(j, "art");
    r.hidden = jbool(j, "hidden");
}

struct Stream {
    int64_t id = 0;
    int streamType = 0;  // 1 video, 2 audio, 3 subtitle
    int64_t index = -1;
    std::string codec;
    std::string language;
    std::string languageTag;
    std::string displayTitle;
    bool selected = false;
    bool isDefault = false;
    bool forced = false;
    int channels = 0;
    std::string key;  // external subtitle: sidecar path (/library/streams/{id})
};
inline void from_json(const nlohmann::json& j, Stream& r) {
    r.id = jint(j, "id");
    r.streamType = (int)jint(j, "streamType");
    r.index = jint(j, "index", -1);
    r.codec = jstr(j, "codec");
    r.language = jstr(j, "language");
    r.languageTag = jstr(j, "languageTag");
    r.displayTitle = jstr(j, "displayTitle", jstr(j, "extendedDisplayTitle"));
    r.selected = jbool(j, "selected");
    r.isDefault = jbool(j, "default");
    r.forced = jbool(j, "forced");
    r.channels = (int)jint(j, "channels");
    r.key = jstr(j, "key");
}

struct Part {
    int64_t id = 0;
    std::string key;  // direct play path: {base}{key}?<token>
    std::string container;
    int64_t size = 0;
    int64_t duration = 0;  // ms
    bool accessible = true;
    bool exists = true;
    std::vector<Stream> streams;
};
inline void from_json(const nlohmann::json& j, Part& r) {
    r.id = jint(j, "id");
    r.key = jstr(j, "key");
    r.container = jstr(j, "container");
    r.size = jint(j, "size");
    r.duration = jint(j, "duration");
    r.accessible = jbool(j, "accessible", true);
    r.exists = jbool(j, "exists", true);
    if (j.contains("Stream") && j["Stream"].is_array()) r.streams = j["Stream"].get<std::vector<Stream>>();
}

/// Nature of a playback source — drives the Stremio source picker's badge and
/// whether the source is directly playable on a console (no torrent engine).
/// Plex/Jellyfin only ever produce Direct.
enum class SourceKind {
    Direct,    // plain HTTP(S) file — playable
    Debrid,    // HTTP(S) link served by a debrid (RealDebrid/AllDebrid…) — playable
    Torrent,   // raw infoHash (no url) — NOT playable here (no local torrent client)
    External,  // externalUrl (browser link) — NOT playable here
    Youtube,   // ytId — NOT playable here on console
};

struct Media {
    int64_t id = 0;
    std::string videoResolution;  // "1080", "4k"...
    std::string videoCodec;
    std::string audioCodec;
    std::string container;
    int64_t bitrate = 0;  // kbps
    int width = 0;
    int height = 0;
    int64_t duration = 0;  // ms
    std::vector<Part> parts;
    // ---- source presentation (Stremio picker; empty/default on Plex/Jellyfin) ----
    std::string label;   // primary line: source/addon name (+ release group)
    std::string detail;  // secondary line: codec · size · seeders (our own re-render)
    SourceKind kind = SourceKind::Direct;
    bool cached = true;  // debrid cache hint (best-effort; ⚡ vs pending). false = uncached
    // A source is directly playable iff it carries a real URL (parts[0].key).
    bool playable() const { return !parts.empty() && !parts.front().key.empty(); }
};
inline void from_json(const nlohmann::json& j, Media& r) {
    r.id = jint(j, "id");
    r.videoResolution = jstr(j, "videoResolution");
    r.videoCodec = jstr(j, "videoCodec");
    r.audioCodec = jstr(j, "audioCodec");
    r.container = jstr(j, "container");
    r.bitrate = jint(j, "bitrate");
    r.width = (int)jint(j, "width");
    r.height = (int)jint(j, "height");
    r.duration = jint(j, "duration");
    if (j.contains("Part") && j["Part"].is_array()) r.parts = j["Part"].get<std::vector<Part>>();
}

struct Chapter {
    std::string tag;              // chapter title
    int64_t startTimeOffset = 0;  // ms
    int64_t endTimeOffset = 0;    // ms
};
inline void from_json(const nlohmann::json& j, Chapter& r) {
    r.tag = jstr(j, "tag");
    r.startTimeOffset = jint(j, "startTimeOffset");
    r.endTimeOffset = jint(j, "endTimeOffset");
}

/// Intro/credits marker (type = "intro" | "credits"; ms)
struct Marker {
    std::string type;
    int64_t startTimeOffset = 0;
    int64_t endTimeOffset = 0;
};
inline void from_json(const nlohmann::json& j, Marker& r) {
    r.type = jstr(j, "type");
    r.startTimeOffset = jint(j, "startTimeOffset");
    r.endTimeOffset = jint(j, "endTimeOffset");
}

struct Role {
    std::string id;    // numeric identifier (person page, filmography)
    std::string tag;   // person name
    std::string role;  // character
    std::string thumb;
};
inline void from_json(const nlohmann::json& j, Role& r) {
    if (j.contains("id")) {
        if (j.at("id").is_number())
            r.id = std::to_string(j.at("id").get<int64_t>());
        else
            r.id = jstr(j, "id");
    }
    r.tag = jstr(j, "tag");
    r.role = jstr(j, "role");
    r.thumb = jstr(j, "thumb");
}

/// Library item (a movie, show, season, episode, clip, collection, playlist...)
struct Item {
    std::string ratingKey;  // opaque id, backend-specific (Plex ratingKey, Jellyfin Id, Stremio tt...)
    std::string key;        // detail path (/library/metadata/{ratingKey})
    std::string guid;       // cross-source identity (plex://, ProviderIds, IMDB id)
    std::string type;       // movie | show | season | episode | clip | collection
    std::string title;
    std::string summary;
    int64_t year = 0;
    std::string thumb;      // relative poster path
    std::string art;        // relative backdrop path
    std::string clearLogo;  // cut-out logo (Image[] array, type clearLogo)
    int64_t duration = 0;    // ms
    int64_t viewOffset = 0;  // ms — resume position
    int64_t viewCount = 0;   // > 0 means watched
    int64_t addedAt = 0;     // epoch s
    int64_t lastViewedAt = 0;
    int64_t watchlistedAt = 0;  // epoch s — provider watchlist state (0 = absent)
    int64_t index = 0;        // episode number (or season number on a season)
    int64_t parentIndex = 0;  // season number (on an episode)
    int64_t leafCount = 0;    // episode count (show/season)
    int64_t viewedLeafCount = 0;
    int64_t childCount = 0;
    // playlists (type "playlist")
    std::string composite;     // 1:1 mosaic generated by the server
    bool smart = false;        // smart playlist (dynamic filter)
    std::string playlistType;  // video | audio | photo — only video ones are playable here
    std::string contentRating;
    double rating = 0.0;          // critic rating 0-10
    double audienceRating = 0.0;  // audience rating 0-10
    std::string ratingImage;          // critic source: imdb://…, rottentomatoes://…, themoviedb://…
    std::string audienceRatingImage;  // audience source
    std::string originallyAvailableAt;  // YYYY-MM-DD
    std::string parentRatingKey;        // season (from an episode)
    std::string parentTitle;
    std::string parentThumb;
    std::string grandparentRatingKey;  // show (from an episode)
    std::string grandparentTitle;
    std::string grandparentThumb;
    std::string grandparentArt;
    std::vector<std::string> genres;
    std::vector<Role> roles;
    std::vector<Role> directors;  // Director: same shape as Role (id/tag/thumb)
    std::vector<Media> media;
    std::vector<Chapter> chapters;
    std::vector<Marker> markers;

    bool played() const { return viewCount > 0; }
};
inline void from_json(const nlohmann::json& j, Item& r) {
    r.ratingKey = jstr(j, "ratingKey", jstr(j, "key"));
    r.key = jstr(j, "key");
    r.guid = jstr(j, "guid");
    r.type = jstr(j, "type");
    r.title = jstr(j, "title");
    r.summary = jstr(j, "summary");
    r.year = jint(j, "year");
    r.thumb = jstr(j, "thumb");
    r.art = jstr(j, "art");
    r.duration = jint(j, "duration");
    r.viewOffset = jint(j, "viewOffset");
    r.viewCount = jint(j, "viewCount");
    r.addedAt = jint(j, "addedAt");
    r.lastViewedAt = jint(j, "lastViewedAt");
    r.watchlistedAt = jint(j, "watchlistedAt");
    r.index = jint(j, "index");
    r.parentIndex = jint(j, "parentIndex");
    r.leafCount = jint(j, "leafCount");
    r.viewedLeafCount = jint(j, "viewedLeafCount");
    r.childCount = jint(j, "childCount");
    r.composite = jstr(j, "composite");
    r.smart = jbool(j, "smart");
    r.playlistType = jstr(j, "playlistType");
    r.contentRating = jstr(j, "contentRating");
    r.rating = jnum(j, "rating");
    r.audienceRating = jnum(j, "audienceRating");
    r.ratingImage = jstr(j, "ratingImage");
    r.audienceRatingImage = jstr(j, "audienceRatingImage");
    r.originallyAvailableAt = jstr(j, "originallyAvailableAt");
    r.parentRatingKey = jstr(j, "parentRatingKey");
    r.parentTitle = jstr(j, "parentTitle");
    r.parentThumb = jstr(j, "parentThumb");
    r.grandparentRatingKey = jstr(j, "grandparentRatingKey");
    r.grandparentTitle = jstr(j, "grandparentTitle");
    r.grandparentThumb = jstr(j, "grandparentThumb");
    r.grandparentArt = jstr(j, "grandparentArt");
    r.genres = jtags(j, "Genre");
    // cut-out logo: Image[{type:"clearLogo"}].url
    if (j.contains("Image") && j["Image"].is_array()) {
        for (auto& e : j["Image"]) {
            if (jstr(e, "type") == "clearLogo") r.clearLogo = jstr(e, "url");
        }
    }
    if (j.contains("Role") && j["Role"].is_array()) r.roles = j["Role"].get<std::vector<Role>>();
    if (j.contains("Director") && j["Director"].is_array()) r.directors = j["Director"].get<std::vector<Role>>();
    if (j.contains("Media") && j["Media"].is_array()) r.media = j["Media"].get<std::vector<Media>>();
    if (j.contains("Chapter") && j["Chapter"].is_array()) r.chapters = j["Chapter"].get<std::vector<Chapter>>();
    if (j.contains("Marker") && j["Marker"].is_array()) r.markers = j["Marker"].get<std::vector<Marker>>();
}

/// Hub row (a titled horizontal row of items)
struct Hub {
    std::string key;
    std::string hubIdentifier;  // e.g. home.continue, home.ondeck
    std::string title;
    std::string type;
    bool more = false;
    std::vector<Item> items;
};
inline void from_json(const nlohmann::json& j, Hub& r) {
    r.key = jstr(j, "key", jstr(j, "hubKey"));
    r.hubIdentifier = jstr(j, "hubIdentifier");
    r.title = jstr(j, "title");
    r.type = jstr(j, "type");
    r.more = jbool(j, "more");
    if (j.contains("Metadata") && j["Metadata"].is_array()) r.items = j["Metadata"].get<std::vector<Item>>();
}

/// Paginated envelope — equivalent of the old Jellyfin Result<T>
/// (Items + total + offset). The Plex from_json reads MediaContainer.
template <typename T>
struct Container {
    std::vector<T> Items;
    long TotalRecordCount = 0;
    long StartIndex = 0;
};

template <typename T>
inline void from_json(const nlohmann::json& j, Container<T>& r) {
    const nlohmann::json& mc = j.contains("MediaContainer") ? j.at("MediaContainer") : j;
    for (const char* key : {"Metadata", "Directory", "Hub", "SearchResult"}) {
        auto it = mc.find(key);
        if (it == mc.end() || !it->is_array()) continue;
        if (strcmp(key, "SearchResult") == 0) {
            // /library/search wraps each result: SearchResult[].Metadata
            for (auto& e : *it)
                if (e.contains("Metadata")) r.Items.push_back(e.at("Metadata").get<T>());
        } else {
            r.Items = it->get<std::vector<T>>();
        }
        break;
    }
    r.StartIndex = (long)jint(mc, "offset");
    r.TotalRecordCount = (long)jint(mc, "totalSize", jint(mc, "size", r.Items.size()));
}

}  // namespace media
