foreach(other IN ITEMS PLATFORM_DESKTOP PLATFORM_IOS PLATFORM_TVOS PLATFORM_ANDROID PLATFORM_PSV PLATFORM_PS4 PLATFORM_SWITCH)
    if (${other})
        message(FATAL_ERROR "PLATFORM_PS5 cannot be combined with ${other}")
    endif ()
endforeach ()
set(PS5_NATIVE_PREFIX "" CACHE PATH "Native media prefix")
set(PS5_NATIVE_RUNTIME "" CACHE PATH "Native runtime prefix")
set(PS5_NATIVE_SDL_PREFIX "" CACHE PATH "Native SDL prefix")
set(PS5_NATIVE_GL_PREFIX "" CACHE PATH "Native graphics prefix")
foreach(prefix IN ITEMS PS5_NATIVE_PREFIX PS5_NATIVE_RUNTIME PS5_NATIVE_SDL_PREFIX PS5_NATIVE_GL_PREFIX)
    if (NOT IS_DIRECTORY "${${prefix}}")
        message(FATAL_ERROR "Set ${prefix} to a prepared native dependency directory")
    endif ()
endforeach ()
find_program(PS5_NATIVE_PYTHON NAMES python3 REQUIRED)
file(GLOB_RECURSE native_translations CONFIGURE_DEPENDS "${CMAKE_CURRENT_SOURCE_DIR}/resources/i18n/*.json")
execute_process(COMMAND "${PS5_NATIVE_PYTHON}" -B "${CMAKE_CURRENT_LIST_DIR}/configure.py"
    --source "${CMAKE_CURRENT_SOURCE_DIR}" --build "${CMAKE_BINARY_DIR}"
    --graphics "${PS5_NATIVE_GL_PREFIX}" --sdl "${PS5_NATIVE_SDL_PREFIX}"
    RESULT_VARIABLE result)
if (NOT result EQUAL 0)
    message(FATAL_ERROR "Native dependency configuration failed")
endif ()
include_directories("${CMAKE_BINARY_DIR}/native-display" "${CMAKE_BINARY_DIR}/native-audio" "${PS5_NATIVE_GL_PREFIX}/include")
set(CMAKE_TOOLCHAIN_FILE "${CMAKE_CURRENT_LIST_DIR}/toolchain.cmake" CACHE FILEPATH "Native archive toolchain")
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(USE_SDL2 ON)
set(USE_GLFW OFF)
set(USE_GL3 ON)
set(USE_GL2 OFF)
set(USE_GLES2 OFF)
set(USE_GLES3 OFF)
set(USE_LIBROMFS OFF)
set(SIMPLE_HIGHLIGHT ON)
set(BRLS_RESOURCES_DIR "/app0")
add_compile_definitions(PS5_NATIVE_GPU=1 PS5_NATIVE_HDR=1 PS5=1 __PS5__=1 SDL_MAIN_HANDLED=1 PS5_NATIVE_DOWNLOAD_DATA_SIZE_MIB=4096)
set(ENV{PKG_CONFIG_PATH} "")
set(ENV{PKG_CONFIG_LIBDIR} "${PS5_NATIVE_SDL_PREFIX}/lib/pkgconfig:${PS5_NATIVE_PREFIX}/lib/pkgconfig")
set(ENV{PKG_CONFIG_SYSROOT_DIR} "")
list(PREPEND CMAKE_PREFIX_PATH "${PS5_NATIVE_SDL_PREFIX}" "${PS5_NATIVE_PREFIX}")

function(ps5_native_export_archives app)
    set(archive_entries "")
    foreach(target IN ITEMS ${app} borealis fmt yogacore tinyxml2 lunasvg plutovg)
        if (TARGET ${target})
            get_target_property(kind ${target} TYPE)
            if (kind STREQUAL "STATIC_LIBRARY")
                list(APPEND archive_entries "\"$<TARGET_FILE:${target}>\"")
            endif ()
        endif ()
    endforeach ()
    string(JOIN ",\n    " archives ${archive_entries})
    file(GLOB media_paths "${PS5_NATIVE_PREFIX}/lib/lib*.a")
    list(SORT media_paths)
    set(media_entries "")
    foreach(path IN LISTS media_paths)
        list(APPEND media_entries "\"${path}\"")
    endforeach ()
    string(JOIN ",\n    " media ${media_entries})
    file(GENERATE OUTPUT "${CMAKE_BINARY_DIR}/native-link.json" CONTENT
"{\n  \"schema\": 1,\n  \"app_archive\": \"$<TARGET_FILE:${app}>\",\n  \"archives\": [\n    ${archives}\n  ],\n  \"media_libraries\": [\n    ${media}\n  ],\n  \"sdl_archive\": \"${PS5_NATIVE_SDL_PREFIX}/lib/libSDL2.a\",\n  \"graphics_prefix\": \"${PS5_NATIVE_GL_PREFIX}\",\n  \"display_config_header\": \"${CMAKE_BINARY_DIR}/native-display/ps5_native_display_config.hpp\",\n  \"audio_config_header\": \"${CMAKE_BINARY_DIR}/native-audio/ps5_native_audio_config.hpp\"\n}\n")
endfunction()

if (NOT DEFINED VERSION_BUILD)
    execute_process(COMMAND git rev-list --count HEAD
        WORKING_DIRECTORY "${CMAKE_CURRENT_SOURCE_DIR}"
        OUTPUT_VARIABLE VERSION_BUILD OUTPUT_STRIP_TRAILING_WHITESPACE
        COMMAND_ERROR_IS_FATAL ANY)
endif ()
