set(CMAKE_SYSTEM_NAME Generic)
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES PS5_NATIVE_RUNTIME PS5_NATIVE_PREFIX PS5_NATIVE_SDL_PREFIX PS5_NATIVE_GL_PREFIX)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
set(PS5_NATIVE_RUNTIME "" CACHE PATH "Native runtime prefix")
set(PS5_NATIVE_SDK "${PS5_NATIVE_RUNTIME}/.deps/native/ps5-payload-sdk")
if (NOT EXISTS "${PS5_NATIVE_SDK}/target/include/stdio.h")
    message(FATAL_ERROR "The native runtime SDK is missing: ${PS5_NATIVE_SDK}")
endif ()
find_program(CMAKE_C_COMPILER NAMES clang-18 REQUIRED)
find_program(CMAKE_CXX_COMPILER NAMES clang++-18 REQUIRED)
find_program(CMAKE_AR NAMES llvm-ar-18 REQUIRED)
find_program(CMAKE_RANLIB NAMES llvm-ranlib-18 REQUIRED)
set(CMAKE_C_COMPILER_TARGET x86_64-sie-ps5)
set(CMAKE_CXX_COMPILER_TARGET x86_64-sie-ps5)
set(native_abi "-fvisibility-nodllstorageclass=default -isysroot ${PS5_NATIVE_SDK} -fno-stack-protector -fno-plt -femulated-tls -ffile-prefix-map=${CMAKE_SOURCE_DIR}=switchfin-source -ffile-prefix-map=${CMAKE_BINARY_DIR}=native-player/cmake")
set(CMAKE_C_FLAGS_INIT "${native_abi} -isystem ${PS5_NATIVE_SDK}/target/include")
# libc++'s C header wrappers must precede the native C headers (matching the CRT).
set(CMAKE_CXX_FLAGS_INIT "${native_abi} -nostdinc++ -isystem ${PS5_NATIVE_SDK}/target/include/c++/v1 -isystem ${PS5_NATIVE_SDK}/target/include -fexceptions -frtti")
set(CMAKE_FIND_ROOT_PATH "${PS5_NATIVE_PREFIX}" "${PS5_NATIVE_SDL_PREFIX}" "${PS5_NATIVE_SDK}/target")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
