#!/usr/bin/env python3
"""Verify native ELF load geometry and preservation of linked application data."""
import argparse
import json
from pathlib import Path
import struct

PT_LOAD = 1
SHT_NOBITS = 8
SHF_ALLOC = 2
# These sections are intentionally regenerated by the native converter.
METADATA = {".dynamic", ".dynsym", ".dynstr", ".gnu.hash", ".hash", ".rela.dyn", ".rela.plt"}


def read_elf(path):
    data = Path(path).read_bytes()
    if len(data) < 64 or data[:7] != b"\x7fELF\x02\x01\x01":
        raise ValueError("requires a little-endian ELF64 image")
    if struct.unpack_from("<H", data, 18)[0] != 62:
        raise ValueError("requires an x86-64 image")
    phoff, shoff = struct.unpack_from("<QQ", data, 32)
    ehsize, phsize, phnum, shsize, shnum, shstr = struct.unpack_from("<HHHHHH", data, 52)
    if ehsize != 64 or (phnum and phsize != 56) or (shnum and shsize != 64):
        raise ValueError("invalid ELF header/table entry size")
    if phoff + phnum * phsize > len(data) or shoff + shnum * shsize > len(data):
        raise ValueError("truncated ELF header table")
    headers = [struct.unpack_from("<IIQQQQQQ", data, phoff + i * phsize) for i in range(phnum)]
    sections = [struct.unpack_from("<IIQQQQIIQQ", data, shoff + i * shsize) for i in range(shnum)]
    names = b""
    if sections:
        if not 0 < shstr < len(sections):
            raise ValueError("invalid section name table")
        off, size = sections[shstr][4:6]
        if off + size > len(data):
            raise ValueError("truncated section name table")
        names = data[off:off + size]
    named = []
    for section in sections:
        name_at = section[0]
        end = names.find(b"\0", name_at)
        if end < 0:
            raise ValueError("invalid section name")
        name = names[name_at:end].decode("ascii")
        if section[1] != SHT_NOBITS and section[4] + section[5] > len(data):
            raise ValueError(f"truncated section: {name}")
        named.append((name, section))
    return data, headers, named


def validate_loads(data, headers):
    loads = [header for header in headers if header[0] == PT_LOAD]
    if not loads:
        raise ValueError("ELF has no load segments")
    for index, (_, _, offset, address, _, file_size, memory_size, alignment) in enumerate(loads):
        if file_size > memory_size or offset + file_size > len(data):
            raise ValueError(f"load segment {index}: invalid file/memory size")
        if alignment > 1:
            if alignment & (alignment - 1):
                raise ValueError(f"load segment {index}: alignment is not a power of two")
            if offset % alignment != address % alignment:
                raise ValueError(f"load segment {index}: file/virtual offsets are not congruent")
    return loads


def mapped_offset(loads, address, size, file_backed=True):
    found = []
    for header in loads:
        offset, base, file_size, memory_size = header[2], header[3], header[5], header[6]
        limit = file_size if file_backed else memory_size
        if base <= address and address + size <= base + limit:
            found.append(offset + address - base)
    if len(found) != 1:
        raise ValueError(f"address 0x{address:x} has {len(found)} load mappings")
    return found[0]


def verify_layout(linked, native):
    original, _, sections = read_elf(linked)
    converted, headers, _ = read_elf(native)
    loads = validate_loads(converted, headers)
    checked = []
    for name, section in sections:
        _, kind, flags, address, offset, size, *_ = section
        if not flags & SHF_ALLOC or not size or name in METADATA:
            continue
        target = mapped_offset(loads, address, size, kind != SHT_NOBITS)
        if kind != SHT_NOBITS and original[offset:offset + size] != converted[target:target + size]:
            raise ValueError(f"native image does not preserve section: {name}")
        if kind == SHT_NOBITS:
            for header in loads:
                start = max(address, header[3])
                end = min(address + size, header[3] + header[5])
                if end > start:
                    at = header[2] + start - header[3]
                    if any(converted[at:at + end - start]):
                        raise ValueError(f"nonzero file data overlaps zero-initialized section: {name}")
        checked.append(name)
    if not checked:
        raise ValueError("linked image has no application sections to verify")
    # Process parameters and unwind descriptors must refer to the same file
    # bytes as their corresponding load mapping, not merely valid file ranges.
    for kind, _, offset, address, _, size, _, _ in headers:
        if kind in (2, 0x61000001, 0x6474E550) and size:
            if mapped_offset(loads, address, size) != offset:
                raise ValueError(f"descriptor 0x{kind:x}: inconsistent load mapping")
    return {"load_segments": len(loads), "preserved_sections": checked}


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("linked", type=Path)
    parser.add_argument("native", type=Path)
    args = parser.parse_args()
    print(json.dumps(verify_layout(args.linked, args.native), indent=2))
