name: mingw-packages

on:
  push:
    tags: [ mingw-packages ]
    paths: [ scripts/mingw64/*/* ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        msystem: [ MINGW64, MINGW32 ]
    runs-on: windows-latest
    env:
      MSYSTEM: ${{ matrix.msystem }}
    defaults:
      run:
        shell: C:\shells\msys2bash.cmd {0}
    steps:
    - name: Disable autocrlf
      shell: bash
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v4
      with:
        sparse-checkout: scripts/mingw64
    - name: Install dependency
      run: |
        pacman -S --needed --noconfirm \
          ${MINGW_PACKAGE_PREFIX}-make \
          ${MINGW_PACKAGE_PREFIX}-autotools \
          ${MINGW_PACKAGE_PREFIX}-cmake \
          ${MINGW_PACKAGE_PREFIX}-ninja \
          ${MINGW_PACKAGE_PREFIX}-meson \
          ${MINGW_PACKAGE_PREFIX}-cc patch p7zip
    - name: Build packages
      run: |
        cd scripts/mingw64

        for pkg in mbedtls libwebp freetype harfbuzz libass dav1d ffmpeg mpv-opengl spirv-cross shaderc mpv; do
          echo building $pkg
          cd $pkg; makepkg-mingw -sciCf --noconfirm; cd ..
        done

        for pkg in glfw curl; do
          echo building $pkg
          cd $pkg; makepkg-mingw -scCf --noconfirm; cd ..
        done

        cd ${MINGW_PREFIX}
        7z a -mx=9 ${GITHUB_WORKSPACE}/mpv-dev-${MSYSTEM_CARCH}.7z include/mpv \
          ${MINGW_PREFIX}/bin/libmpv-2.dll \
          ${MINGW_PREFIX}/lib/libmpv.dll.a \
          ${MINGW_PREFIX}/share/doc/mpv/mpv.def
    - name: Upload packages
      uses: softprops/action-gh-release@v2
      with:
        name: mingw-packages
        tag_name: mingw-packages
        prerelease: true
        files: |
          scripts/mingw64/curl/*.pkg.tar.zst
          scripts/mingw64/glfw/*.pkg.tar.zst
          scripts/mingw64/libwebp/*.pkg.tar.zst
          scripts/mingw64/mpv/*.pkg.tar.zst
          scripts/mingw64/mpv-opengl/*.pkg.tar.zst
          mpv-*.7z
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/mingw-packages/total?label=Downloads)