name: mingw-packages

on:
  push:
    tags: [ mingw-packages ]
    branches: [ mingw, mpv ]

permissions:
  contents: write

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
        - { sys: mingw64, env: x86_64 }
        - { sys: mingw32, env: i686 }
        - { sys: clangarm64, env: clang-aarch64 }
        sys: [ mingw64, mingw32, clangarm64 ]
    runs-on: ${{ contains(matrix.sys, 'arm64') && 'windows-11-arm' || 'windows-latest' }}
    defaults:
      run:
        shell: msys2 {0}
    steps:
    - name: Disable autocrlf
      shell: bash
      run: git config --global core.autocrlf false
    - uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ matrix.sys }}
        cache: false
        release: ${{ contains(matrix.sys, 'arm64') }}
        install: >-
          patch
          lzip
          unzip
          make
          diffutils
          mingw-w64-${{ matrix.env }}-nasm
          mingw-w64-${{ matrix.env }}-meson
          mingw-w64-${{ matrix.env }}-cmake
          mingw-w64-${{ matrix.env }}-cc
    - uses: actions/checkout@v4
      with:
        sparse-checkout: scripts/mingw64
    - name: Build packages
      run: |
        cd scripts/mingw64

        for pkg in mbedtls libssh2 freetype harfbuzz libass dav1d ffmpeg spirv-headers spirv-tools glslang spirv-cross shaderc libplacebo; do
          echo building $pkg
          pushd $pkg; makepkg-mingw -sciCf --noconfirm; popd
        done

        for pkg in mpv glfw libwebp curl; do
          echo building $pkg
          pushd $pkg; makepkg-mingw -scCf --noconfirm; popd
        done
    - name: Upload packages
      uses: softprops/action-gh-release@v2
      with:
        name: mingw-packages
        tag_name: mingw-packages
        prerelease: true
        files: |
          scripts/mingw64/curl/*.pkg.tar.zst
          scripts/mingw64/glfw/*.pkg.tar.zst
          scripts/mingw64/libwebp/*.pkg.tar.zst
          scripts/mingw64/mpv/*.pkg.tar.zst
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/mingw-packages/total?label=Downloads)