name: switch-portlibs

on:
  push:
    tags: [ switch-portlibs ]
    branches: [ deko3d, mpv ]

permissions:
  contents: write

jobs:
  build-portlibs:
    runs-on: ubuntu-latest
    container:
      image: devkitpro/devkita64:20260219
    steps:
    - name: Disable autocrlf
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v6
      with:
        sparse-checkout: scripts/switch
    - name: Install dependency
      run: |
        apt-get update
        apt-get install -y fakeroot zstd bison flex libtool python3-mako meson manpages-
    - name: Build portlibs
      run: |
        adduser --gecos '' --home ${GITHUB_WORKSPACE}/scripts/switch --disabled-password builder
        echo 'builder ALL=(ALL) NOPASSWD:ALL' > /etc/sudoers.d/builder

        chown -R builder:builder scripts/switch
        for pkg in mbedtls libssh2 dav1d ffmpeg libuam; do
          echo building $pkg
          su - builder -c "cd $pkg && dkp-makepkg -siCf --noconfirm"
        done
        for pkg in mpv curl nspmini hacbrewpack; do
          echo building $pkg
          su - builder -c "cd $pkg && dkp-makepkg -sCf --noconfirm"
        done

    - name: Upload portlibs
      uses: softprops/action-gh-release@v3
      with:
        name: switch-portlibs
        tag_name: switch-portlibs
        prerelease: true
        files: scripts/switch/*/*.pkg.tar.zst
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/switch-portlibs/total?label=Downloads)