name: vita-packages

on:
  push:
    tags: [ vita-packages ]
    branches: [ gxm, mpv ]

permissions:
  contents: write

jobs:
  build-packages:
    runs-on: ubuntu-latest
    container:
      image: vitasdk/vitasdk:2026.08
    steps:
    - uses: actions/checkout@v6
      with:
        sparse-checkout: scripts/vita
    - name: Install dependency
      run: |
        apt-get update
        apt-get install -y meson
    - name: Build packages
      run: |
        chown -R vitasdk:vitasdk scripts/vita
        su -p vitasdk -s /bin/bash <<'EOF'
          export PATH=$VITASDK/bin:$PATH
          cd $GITHUB_WORKSPACE/scripts/vita

          for pkg in mbedtls ffmpeg mpv mupdf curl; do
            pushd ${pkg}
            vita-makepkg -siCf --noconfirm
            popd
          done
        EOF
    - name: Upload packages
      uses: softprops/action-gh-release@v3
      with:
        name: vita-packages
        tag_name: vita-packages
        prerelease: true
        files: scripts/vita/*/*.pkg.tar.xz
        body: |
          ![download](https://img.shields.io/github/downloads/${{ github.repository }}/vita-packages/total?label=Downloads)